services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sms-sql
    environment:
      SA_PASSWORD: "YourStrong@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    build:
      context: ./src/backend/SMS_Backend
      dockerfile: Dockerfile
    container_name: sms-api
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sms-sql;Database=SchoolManagementDB;User Id=sa;Password=YourStrong@123;TrustServerCertificate=True;
    depends_on:
      - sqlserver

volumes:
  sql_data:
