using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SMS_Backend.Data;
using SMS_Backend.Models;
using System.Security.Claims;
using System.Text;

namespace SMS_Backend.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    [Authorize(Roles = "Admin")]
    public class ReportController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        public ReportController(ApplicationDbContext context) => _context = context;

        private int GetCurrentUserId() =>
            int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);

        [HttpGet]
        public async Task<IActionResult> GetAllReports() =>
            Ok(await _context.Reports.Include(r => r.Admin)
                .Select(r => new
                {
                    r.ReportId,
                    r.Type,
                    r.GeneratedOn,
                    r.FilePath,
                    GeneratedBy = new { r.Admin.FirstName, r.Admin.LastName }
                })
                .OrderByDescending(r => r.GeneratedOn)
                .ToListAsync());

        [HttpGet("{id}")]
        public async Task<IActionResult> GetReport(int id)
        {
            var report = await _context.Reports.Include(r => r.Admin)
                .FirstOrDefaultAsync(r => r.ReportId == id);
            if (report == null) return NotFound(new { message = "Report not found." });
            return Ok(report);
        }

        // ── GET: api/report/download?path=... ─────────────────────────────
        // Returns the stored report file as a downloadable stream.
        // NOTE: In production, serve from blob storage. Here we stream from
        //       the in-memory generated content stored in FilePath metadata.
        [HttpGet("download")]
        public async Task<IActionResult> DownloadReport([FromQuery] string path)
        {
            if (string.IsNullOrWhiteSpace(path))
                return BadRequest(new { message = "path parameter is required." });

            // Look up the report by its stored FilePath
            var report = await _context.Reports.FirstOrDefaultAsync(r => r.FilePath == path);
            if (report == null)
                return NotFound(new { message = "Report record not found for this path." });

            // Re-generate the content on the fly from stored type
            // (since we store metadata only, not the file bytes)
            var content = $"Report Type : {report.Type}\r\n" +
                          $"Generated On: {report.GeneratedOn:yyyy-MM-dd HH:mm} UTC\r\n" +
                          $"File Path   : {report.FilePath}\r\n\r\n" +
                          "This report was generated by the SMS system.\r\n" +
                          "Please regenerate for latest data.";

            var fileName = Path.GetFileName(path);
            var bytes = Encoding.UTF8.GetBytes(content);
            return File(bytes, "text/plain", fileName);
        }

        [HttpPost("attendance")]
        public async Task<IActionResult> GenerateAttendanceReport(
            [FromQuery] string? className,
            [FromQuery] DateTime? from,
            [FromQuery] DateTime? to)
        {
            var query = _context.Attendances.Include(a => a.Student).AsQueryable();
            if (!string.IsNullOrEmpty(className)) query = query.Where(a => a.Student.Class == className);
            if (from.HasValue) query = query.Where(a => a.Date >= from.Value);
            if (to.HasValue) query = query.Where(a => a.Date <= to.Value);

            var records = await query.OrderBy(a => a.Student.RollNumber).ThenBy(a => a.Date).ToListAsync();
            var sb = new StringBuilder();
            sb.AppendLine("ATTENDANCE REPORT");
            sb.AppendLine($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
            if (!string.IsNullOrEmpty(className)) sb.AppendLine($"Class: {className}");
            if (from.HasValue) sb.AppendLine($"From: {from.Value:yyyy-MM-dd}");
            if (to.HasValue) sb.AppendLine($"To:   {to.Value:yyyy-MM-dd}");
            sb.AppendLine(new string('-', 60));
            sb.AppendLine($"{"Roll No",-12} {"Name",-25} {"Date",-12} {"Status"}");
            sb.AppendLine(new string('-', 60));
            foreach (var a in records)
                sb.AppendLine($"{a.Student.RollNumber,-12} {a.Student.FirstName + " " + a.Student.LastName,-25} {a.Date:yyyy-MM-dd,-12} {a.Status}");
            sb.AppendLine(new string('-', 60));
            sb.AppendLine($"Total Records: {records.Count}");

            return await SaveAndReturnReport("Attendance", sb.ToString());
        }

        [HttpPost("marks")]
        public async Task<IActionResult> GenerateMarksReport(
            [FromQuery] string? className,
            [FromQuery] string? subject,
            [FromQuery] string? exam)
        {
            var query = _context.Marks.Include(m => m.Student).AsQueryable();
            if (!string.IsNullOrEmpty(className)) query = query.Where(m => m.Student.Class == className);
            if (!string.IsNullOrEmpty(subject)) query = query.Where(m => m.Subject == subject);
            if (!string.IsNullOrEmpty(exam)) query = query.Where(m => m.Exam == exam);

            var records = await query.OrderBy(m => m.Student.RollNumber).ToListAsync();
            var sb = new StringBuilder();
            sb.AppendLine("MARKS REPORT");
            sb.AppendLine($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
            sb.AppendLine(new string('-', 70));
            sb.AppendLine($"{"Roll No",-12} {"Name",-25} {"Subject",-15} {"Exam",-12} {"Marks",-10} Pct");
            sb.AppendLine(new string('-', 70));
            foreach (var m in records)
                sb.AppendLine($"{m.Student.RollNumber,-12} {m.Student.FirstName + " " + m.Student.LastName,-25} {m.Subject,-15} {m.Exam,-12} {m.MarksObtained}/{m.TotalMarks,-5} {m.Percentage:F1}%");
            if (records.Any()) sb.AppendLine($"Class Average: {records.Average(m => (double)m.Percentage):F1}%");
            sb.AppendLine($"Total Records: {records.Count}");

            return await SaveAndReturnReport("Marks", sb.ToString());
        }

        [HttpPost("risk")]
        public async Task<IActionResult> GenerateRiskReport([FromQuery] RiskLevel? level)
        {
            var query = _context.RiskMonitorings.Include(r => r.Student).AsQueryable();
            if (level.HasValue) query = query.Where(r => r.RiskLevel == level.Value);

            var latest = await query
                .GroupBy(r => r.StudentId)
                .Select(g => g.OrderByDescending(r => r.MonitoredOn).First())
                .ToListAsync();

            var sb = new StringBuilder();
            sb.AppendLine("RISK MONITORING REPORT");
            sb.AppendLine($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
            sb.AppendLine(new string('-', 70));
            sb.AppendLine($"{"Roll No",-12} {"Name",-25} {"Class",-10} {"Risk Level",-12} Assessed");
            sb.AppendLine(new string('-', 70));
            foreach (var r in latest.OrderByDescending(r => r.RiskLevel))
                sb.AppendLine($"{r.Student.RollNumber,-12} {r.Student.FirstName + " " + r.Student.LastName,-25} {r.Student.Class,-10} {r.RiskLevel,-12} {r.MonitoredOn:yyyy-MM-dd}");
            sb.AppendLine(new string('-', 70));
            sb.AppendLine($"High: {latest.Count(r => r.RiskLevel == RiskLevel.High)} | Medium: {latest.Count(r => r.RiskLevel == RiskLevel.Medium)} | Low: {latest.Count(r => r.RiskLevel == RiskLevel.Low)} | Total: {latest.Count}");

            return await SaveAndReturnReport("Risk", sb.ToString());
        }

        [HttpPost("portfolio")]
        public async Task<IActionResult> GeneratePortfolioReport([FromQuery] string? className)
        {
            var query = _context.StudentPortfolios.Include(p => p.Student).AsQueryable();
            if (!string.IsNullOrEmpty(className)) query = query.Where(p => p.Student.Class == className);

            var portfolios = await query.OrderBy(p => p.Student.RollNumber).ToListAsync();
            var sb = new StringBuilder();
            sb.AppendLine("PORTFOLIO SUMMARY REPORT");
            sb.AppendLine($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
            sb.AppendLine(new string('=', 60));
            foreach (var p in portfolios)
            {
                sb.AppendLine($"Student: {p.Student.FirstName} {p.Student.LastName} | Roll: {p.Student.RollNumber} | Class: {p.Student.Class}");
                sb.AppendLine($"  Attendance  : {p.AttendanceSummary ?? "N/A"}");
                sb.AppendLine($"  Marks       : {p.MarksSummary ?? "N/A"}");
                sb.AppendLine($"  Achievements: {p.AchievementsSummary ?? "N/A"}");
                sb.AppendLine($"  Behavior    : {p.BehaviorSummary ?? "N/A"}");
                sb.AppendLine(new string('-', 60));
            }
            sb.AppendLine($"Total: {portfolios.Count}");

            return await SaveAndReturnReport("Portfolio", sb.ToString());
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteReport(int id)
        {
            var report = await _context.Reports.FindAsync(id);
            if (report == null) return NotFound(new { message = "Report not found." });
            _context.Reports.Remove(report);
            await _context.SaveChangesAsync();
            return Ok(new { message = "Report deleted." });
        }

        private async Task<IActionResult> SaveAndReturnReport(string type, string content)
        {
            var admin = await _context.Admins.FirstOrDefaultAsync(a => a.UserId == GetCurrentUserId());
            if (admin == null) return BadRequest(new { message = "Admin profile not found." });

            var fileName = $"{type}_Report_{DateTime.UtcNow:yyyyMMdd_HHmmss}.txt";
            var filePath = Path.Combine("Reports", fileName);

            _context.Reports.Add(new Report
            {
                AdminId = admin.AdminId,
                Type = type,
                GeneratedOn = DateTime.UtcNow,
                FilePath = filePath
            });
            await _context.SaveChangesAsync();

            return File(Encoding.UTF8.GetBytes(content), "text/plain", fileName);
        }
    }
}
//using Microsoft.AspNetCore.Authorization;
//using Microsoft.AspNetCore.Mvc;
//using Microsoft.EntityFrameworkCore;
//using SMS_Backend.Data;
//using SMS_Backend.Models;
//using System.Security.Claims;
//using System.Text;
//using iText.Kernel.Pdf;
//using iText.Layout;
//using iText.Layout.Element;

//namespace SMS_Backend.Controllers
//{
//    [ApiController]
//    [Route("api/[controller]")]
//    [Authorize(Roles = "Admin")]
//    public class ReportController : ControllerBase
//    {
//        private readonly ApplicationDbContext _context;

//        public ReportController(ApplicationDbContext context)
//        {
//            _context = context;
//        }

//        private int GetCurrentUserId()
//            => int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);

//        // ---------------- GET ALL REPORTS ----------------
//        [HttpGet]
//        public async Task<IActionResult> GetAllReports()
//        {
//            var reports = await _context.Reports
//                .Include(r => r.Admin)
//                .Select(r => new
//                {
//                    r.ReportId,
//                    r.Type,
//                    r.GeneratedOn,
//                    r.FilePath,
//                    GeneratedBy = r.Admin != null
//                        ? new { r.Admin.FirstName, r.Admin.LastName }
//                        : null
//                })
//                .OrderByDescending(r => r.GeneratedOn)
//                .ToListAsync();

//            return Ok(reports);
//        }

//        // ---------------- GET SINGLE REPORT ----------------
//        [HttpGet("{id}")]
//        public async Task<IActionResult> GetReport(int id)
//        {
//            var report = await _context.Reports
//                .Include(r => r.Admin)
//                .FirstOrDefaultAsync(r => r.ReportId == id);

//            if (report == null)
//                return NotFound(new { message = "Report not found." });

//            return Ok(report);
//        }

//        // ---------------- ATTENDANCE REPORT ----------------
//        [HttpPost("attendance")]
//        public async Task<IActionResult> GenerateAttendanceReport(
//            [FromQuery] string? className,
//            [FromQuery] DateTime? from,
//            [FromQuery] DateTime? to)
//        {
//            var query = _context.Attendances
//                .Include(a => a.Student)
//                .AsQueryable();

//            if (!string.IsNullOrEmpty(className))
//                query = query.Where(a => a.Student.Class == className);

//            if (from.HasValue)
//                query = query.Where(a => a.Date >= from.Value);

//            if (to.HasValue)
//                query = query.Where(a => a.Date <= to.Value);

//            var records = await query
//                .OrderBy(a => a.Student.RollNumber)
//                .ToListAsync();

//            var sb = new StringBuilder();
//            sb.AppendLine("ATTENDANCE REPORT");
//            sb.AppendLine($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
//            sb.AppendLine(new string('-', 60));

//            foreach (var a in records)
//            {
//                if (a.Student == null) continue;

//                sb.AppendLine($"{a.Student.RollNumber} | " +
//                              $"{a.Student.FirstName} {a.Student.LastName} | " +
//                              $"{a.Date:yyyy-MM-dd} | {a.Status}");
//            }

//            sb.AppendLine($"Total Records: {records.Count}");

//            return await SaveAndReturnReport("Attendance", sb.ToString());
//        }

//        // ---------------- MARKS REPORT ----------------
//        [HttpPost("marks")]
//        public async Task<IActionResult> GenerateMarksReport(
//            [FromQuery] string? className,
//            [FromQuery] string? subject,
//            [FromQuery] string? exam)
//        {
//            var query = _context.Marks
//                .Include(m => m.Student)
//                .AsQueryable();

//            if (!string.IsNullOrEmpty(className))
//                query = query.Where(m => m.Student.Class == className);

//            if (!string.IsNullOrEmpty(subject))
//                query = query.Where(m => m.Subject == subject);

//            if (!string.IsNullOrEmpty(exam))
//                query = query.Where(m => m.Exam == exam);

//            var records = await query
//                .OrderBy(m => m.Student.RollNumber)
//                .ToListAsync();

//            var sb = new StringBuilder();
//            sb.AppendLine("MARKS REPORT");
//            sb.AppendLine($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
//            sb.AppendLine(new string('-', 70));

//            foreach (var m in records)
//            {
//                if (m.Student == null) continue;

//                sb.AppendLine($"{m.Student.RollNumber} | " +
//                              $"{m.Student.FirstName} {m.Student.LastName} | " +
//                              $"{m.Subject} | {m.Exam} | " +
//                              $"{m.MarksObtained}/{m.TotalMarks} | {m.Percentage}%");
//            }

//            if (records.Any())
//            {
//                var avg = records.Average(x => (double)x.Percentage);
//                sb.AppendLine($"Class Average: {avg:F1}%");
//            }
//            else
//            {
//                sb.AppendLine("Class Average: N/A");
//            }

//            return await SaveAndReturnReport("Marks", sb.ToString());
//        }

//        // ---------------- RISK REPORT ----------------
//        [HttpPost("risk")]
//        public async Task<IActionResult> GenerateRiskReport([FromQuery] RiskLevel? level)
//        {
//            var query = _context.RiskMonitorings
//                .Include(r => r.Student)
//                .AsQueryable();

//            if (level.HasValue)
//                query = query.Where(r => r.RiskLevel == level.Value);

//            var latest = await query
//                .GroupBy(r => r.StudentId)
//                .Select(g => g.OrderByDescending(r => r.MonitoredOn).First())
//                .ToListAsync();

//            var sb = new StringBuilder();
//            sb.AppendLine("RISK REPORT");
//            sb.AppendLine($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
//            sb.AppendLine(new string('-', 70));

//            foreach (var r in latest)
//            {
//                if (r.Student == null) continue;

//                sb.AppendLine($"{r.Student.RollNumber} | " +
//                              $"{r.Student.FirstName} {r.Student.LastName} | " +
//                              $"{r.Student.Class} | {r.RiskLevel} | " +
//                              $"{r.MonitoredOn:yyyy-MM-dd}");
//            }

//            sb.AppendLine($"High: {latest.Count(x => x.RiskLevel == RiskLevel.High)}");
//            sb.AppendLine($"Medium: {latest.Count(x => x.RiskLevel == RiskLevel.Medium)}");
//            sb.AppendLine($"Low: {latest.Count(x => x.RiskLevel == RiskLevel.Low)}");

//            return await SaveAndReturnReport("Risk", sb.ToString());
//        }

//        // ---------------- PORTFOLIO REPORT ----------------
//        [HttpPost("portfolio")]
//        public async Task<IActionResult> GeneratePortfolioReport([FromQuery] string? className)
//        {
//            var query = _context.StudentPortfolios
//                .Include(p => p.Student)
//                .AsQueryable();

//            if (!string.IsNullOrEmpty(className))
//                query = query.Where(p => p.Student.Class == className);

//            var portfolios = await query
//                .OrderBy(p => p.Student.RollNumber)
//                .ToListAsync();

//            var sb = new StringBuilder();
//            sb.AppendLine("PORTFOLIO REPORT");
//            sb.AppendLine($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
//            sb.AppendLine(new string('-', 60));

//            foreach (var p in portfolios)
//            {
//                if (p.Student == null) continue;

//                sb.AppendLine($"{p.Student.FirstName} {p.Student.LastName} | {p.Student.Class}");
//                sb.AppendLine($"Attendance: {p.AttendanceSummary ?? "N/A"}");
//                sb.AppendLine($"Marks: {p.MarksSummary ?? "N/A"}");
//                sb.AppendLine($"Achievements: {p.AchievementsSummary ?? "N/A"}");
//                sb.AppendLine($"Behavior: {p.BehaviorSummary ?? "N/A"}");
//                sb.AppendLine(new string('-', 40));
//            }

//            return await SaveAndReturnReport("Portfolio", sb.ToString());
//        }

//        // ---------------- DELETE REPORT ----------------
//        [HttpDelete("{id}")]
//        public async Task<IActionResult> DeleteReport(int id)
//        {
//            var report = await _context.Reports.FindAsync(id);

//            if (report == null)
//                return NotFound(new { message = "Report not found." });

//            _context.Reports.Remove(report);
//            await _context.SaveChangesAsync();

//            return Ok(new { message = "Report deleted." });
//        }

//        // ---------------- DOWNLOAD REPORT ----------------
//        [HttpGet("download")]
//        public IActionResult Download([FromQuery] string path)
//        {
//            if (string.IsNullOrEmpty(path))
//                return BadRequest("Invalid path");

//            var fullPath = Path.Combine(Directory.GetCurrentDirectory(), path);

//            if (!System.IO.File.Exists(fullPath))
//                return NotFound("File not found");

//            var bytes = System.IO.File.ReadAllBytes(fullPath);

//            return File(bytes, "application/pdf", Path.GetFileName(fullPath));
//        }

//        // ---------------- SAVE + GENERATE PDF ----------------
//        private async Task<IActionResult> SaveAndReturnReport(string type, string content)
//        {
//            var currentUserId = GetCurrentUserId();
//            var admin = await _context.Admins.FirstOrDefaultAsync(a => a.UserId == currentUserId);

//            if (admin == null)
//                return BadRequest(new { message = "Admin profile not found." });

//            var fileName = $"{type}_Report_{DateTime.UtcNow:yyyyMMdd_HHmmss}.pdf";
//            var folderPath = Path.Combine(Directory.GetCurrentDirectory(), "Reports");

//            if (!Directory.Exists(folderPath))
//                Directory.CreateDirectory(folderPath);

//            var filePath = Path.Combine(folderPath, fileName);
//            var writer = new PdfWriter(filePath, new WriterProperties());

//            using (var pdf = new PdfDocument(writer))
//            using (var doc = new Document(pdf))
//            {
//                doc.Add(new Paragraph($"{type.ToUpper()} REPORT"));
//                doc.Add(new Paragraph($"Generated: {DateTime.UtcNow} UTC"));
//                doc.Add(new Paragraph("-----------------------------------"));
//                doc.Add(new Paragraph(content));
//            }

//            var report = new Report
//            {
//                AdminId = admin.AdminId,
//                Type = type,
//                GeneratedOn = DateTime.UtcNow,
//                FilePath = Path.Combine("Reports", fileName)
//            };

//            _context.Reports.Add(report);
//            await _context.SaveChangesAsync();

//            var bytes = await System.IO.File.ReadAllBytesAsync(filePath);

//            return File(bytes, "application/pdf", fileName);
//        }
//    }
//}
